### ISSUE TITLE
Fetch playlist's tracks api call

### ISSUE THREAD

**Issue by mikhailperevoznyk** [beatlink-epfl/beatlink#140]
Write the api call in the SpotifyApiViewModel for tracks in the given playlist.
- The call should fetch all the tracks of a given playlist id
- The fetched tracks should be fetched in SpotifyTrack format

**Comment by arthur-wolf** [comment]
Since this API call will only be used to display a preview of a playlist's tracks and not necessarily all of them, the function will only return the first 50 tracks of a playlist. Check the PR for additional information (https://github.com/beatlink-epfl/beatlink/pull/172)
