### ISSUE TITLE
Create Shared Playlists UI

### ISSUE THREAD

**Issue by mikhailperevoznyk** [beatlink-epfl/beatlink#152]
Create the UI for the shared playlists feature of the app
- The shared playlists should appear as in the figma, with at title "Shared Playlists" and should be displayed one under the other in a column structure
- The shared playlist displayed should have the required info as in the figma for the overview

**Comment by lunasrc** [comment]
I separated the shared playlists to 2 sections: 
- one that groups all the playlists that are shared with me
- one that groups all the public playlists
